import { StrictMode, Suspense } from 'react';
import ReactDOM from 'react-dom/client';
import { createRouter } from '@tanstack/react-router';

import * as Sentry from '@sentry/react';

/**
 * Import the generated route tree
 * This is auto-generated by TanStack Router and contains all application routes
 */
import { routeTree } from './routeTree.gen';
import App from './App';
import NotFound from './pages/NotFound';
import { initGA } from './utils/googleAnalytics';

/**
 * Initialize Sentry for error tracking and performance monitoring
 * Configure different sampling rates based on environment
 */
Sentry.init({
  dsn: 'https://b6b3174913911265fd41aeaa40500ae8@sentry.yorkdevs.link/68',
  environment: import.meta.env.VITE_ENVIRONMENT,
  integrations: [
    Sentry.browserTracingIntegration(),
    Sentry.replayIntegration(),
  ],
  tracesSampleRate: 1.0,
  tracePropagationTargets: [
    // 'localhost',
    `https://${import.meta.env.VITE_ENVIRONMENT === 'prod' ? '' : import.meta.env.VITE_ENVIRONMENT}.app.solverein.io/`,
  ],
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1.0,
});

/**
 * Create the application router using TanStack Router
 * @description Initializes router with the generated route tree
 */
const router = createRouter({
  routeTree,
  defaultNotFoundComponent: NotFound,
});

/**
 * Register the router instance for TypeScript type safety
 * This enhances type checking for router-related code throughout the application
 */
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

/**
 * Mount the application to the DOM
 * Only renders if the root element doesn't already have children
 * This prevents duplicate mounting during development
 */
const rootElement = document.getElementById('root')!;
if (!rootElement.hasChildNodes()) {
  // Initialize GA before render
  initGA();

  const root = ReactDOM.createRoot(rootElement);
  root.render(
    <StrictMode>
      <Suspense fallback="loading">
        <App router={router} />
      </Suspense>

      {/* <RouterProvider router={router} /> */}
    </StrictMode>
  );
}
