/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as ClearmeVerificationRouteImport } from './routes/clearme-verification'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppUserManagementRouteImport } from './routes/_app/user-management'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRolesManagementRouteImport } from './routes/_app/roles-management'
import { Route as AppMyTasksRouteImport } from './routes/_app/my-tasks'
import { Route as AppKpisRouteImport } from './routes/_app/kpis'
import { Route as AppHelpSupportRouteImport } from './routes/_app/help-support'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditReportsRouteImport } from './routes/_app/audit-reports'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/organization/index'
import { Route as AppOrganizationAdminIndexRouteImport } from './routes/_app/organization-admin/index'
import { Route as AppMedicalRecordsIndexRouteImport } from './routes/_app/medical-records/index'
import { Route as AppMedicalChronologyIndexRouteImport } from './routes/_app/medical-chronology/index'
import { Route as AppMasterChronologyIndexRouteImport } from './routes/_app/master-chronology/index'
import { Route as AppCaseManagementIndexRouteImport } from './routes/_app/case-management/index'
import { Route as AppBillingChronologyIndexRouteImport } from './routes/_app/billing-chronology/index'
import { Route as AuthRegisterLayoutRouteImport } from './routes/auth/register/_layout'
import { Route as AuthPatientRegisterLayoutRouteImport } from './routes/auth/patient-register/_layout'
import { Route as AuthLegalUserRegisterLayoutRouteImport } from './routes/auth/legal-user-register/_layout'
import { Route as AppOrganizationManageAllUsersApprovalsRouteImport } from './routes/_app/organization/manage-all-users-approvals'
import { Route as AppOrganizationAdminManageApprovalsRouteImport } from './routes/_app/organization-admin/manage-approvals'
import { Route as AppMedicalRecordsRequestRouteImport } from './routes/_app/medical-records/request'
import { Route as AppKpisTimeSavingKpisRouteImport } from './routes/_app/kpis/time-saving-kpis'
import { Route as AppKpisTimeBasedKpisRouteImport } from './routes/_app/kpis/time-based-kpis'
import { Route as AppKpisProductivityEfficiencyKpisRouteImport } from './routes/_app/kpis/productivity-efficiency-kpis'
import { Route as AppKpisProductivityBasedKpisRouteImport } from './routes/_app/kpis/productivity-based-kpis'
import { Route as AppKpisOperationalEfficiencyRouteImport } from './routes/_app/kpis/operational-efficiency'
import { Route as AppKpisCustomerUsageEngagementRouteImport } from './routes/_app/kpis/customer-usage-engagement'
import { Route as AppKpisCustomerSatisfactionRetentionRouteImport } from './routes/_app/kpis/customer-satisfaction-retention'
import { Route as AppKpisCostSavingRoiRouteImport } from './routes/_app/kpis/cost-saving-roi'
import { Route as AppCaseManagementAddCaseRouteImport } from './routes/_app/case-management/add-case'
import { Route as AuthRegisterLayoutIndexRouteImport } from './routes/auth/register/_layout/index'
import { Route as AuthPatientRegisterLayoutIndexRouteImport } from './routes/auth/patient-register/_layout/index'
import { Route as AuthLegalUserRegisterLayoutIndexRouteImport } from './routes/auth/legal-user-register/_layout/index'
import { Route as AppSettingsProfileOverviewIndexRouteImport } from './routes/_app/settings/profile-overview/index'
import { Route as AppSettingsAccountSettingsIndexRouteImport } from './routes/_app/settings/account-settings/index'
import { Route as AuthRegisterLayoutSupervisingDetailsRouteImport } from './routes/auth/register/_layout/supervising-details'
import { Route as AuthRegisterLayoutRoleSelectionRouteImport } from './routes/auth/register/_layout/role-selection'
import { Route as AuthRegisterLayoutOtpValidationRouteImport } from './routes/auth/register/_layout/otp-validation'
import { Route as AuthRegisterLayoutBusinessDetailsRouteImport } from './routes/auth/register/_layout/business-details'
import { Route as AuthPatientRegisterLayoutBasicDetailsRouteImport } from './routes/auth/patient-register/_layout/basic-details'
import { Route as AuthLegalUserRegisterLayoutBasicDetailsRouteImport } from './routes/auth/legal-user-register/_layout/basic-details'
import { Route as AppSettingsProfileOverviewEditRouteImport } from './routes/_app/settings/profile-overview/edit'
import { Route as AppOrganizationUsersIdRouteImport } from './routes/_app/organization/users.$id'
import { Route as AppMedicalRecordsViewIdRouteImport } from './routes/_app/medical-records/view.$id'
import { Route as AppMedicalRecordsCaseIdRouteImport } from './routes/_app/medical-records/case.$id'
import { Route as AppMedicalChronologyTimelineIdRouteImport } from './routes/_app/medical-chronology/timeline.$id'
import { Route as AppMasterChronologyTimelineIdRouteImport } from './routes/_app/master-chronology/timeline/$id'
import { Route as AppCaseManagementViewIdRouteImport } from './routes/_app/case-management/view.$id'
import { Route as AppCaseManagementTaskIdRouteImport } from './routes/_app/case-management/task.$id'
import { Route as AppCaseManagementEditIdRouteImport } from './routes/_app/case-management/edit.$id'
import { Route as AppBillingChronologyTimelineIdRouteImport } from './routes/_app/billing-chronology/timeline.$id'
import { Route as AppMedicalChronologyTimelineEventChronologyIdIdRouteImport } from './routes/_app/medical-chronology/timeline-event.$chronologyId.$id'
import { Route as AppBillingChronologyBillingEventChronologyIDIdRouteImport } from './routes/_app/billing-chronology/billing-event.$chronologyID.$id'

const AuthRegisterRouteImport = createFileRoute('/auth/register')()
const AuthPatientRegisterRouteImport = createFileRoute(
  '/auth/patient-register',
)()
const AuthLegalUserRegisterRouteImport = createFileRoute(
  '/auth/legal-user-register',
)()

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearmeVerificationRoute = ClearmeVerificationRouteImport.update({
  id: '/clearme-verification',
  path: '/clearme-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientRegisterRoute = AuthPatientRegisterRouteImport.update({
  id: '/patient-register',
  path: '/patient-register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLegalUserRegisterRoute = AuthLegalUserRegisterRouteImport.update({
  id: '/legal-user-register',
  path: '/legal-user-register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppUserManagementRoute = AppUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesManagementRoute = AppRolesManagementRouteImport.update({
  id: '/roles-management',
  path: '/roles-management',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTasksRoute = AppMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpSupportRoute = AppHelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditReportsRoute = AppAuditReportsRouteImport.update({
  id: '/audit-reports',
  path: '/audit-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationAdminIndexRoute =
  AppOrganizationAdminIndexRouteImport.update({
    id: '/organization-admin/',
    path: '/organization-admin/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMedicalRecordsIndexRoute = AppMedicalRecordsIndexRouteImport.update({
  id: '/medical-records/',
  path: '/medical-records/',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalChronologyIndexRoute =
  AppMedicalChronologyIndexRouteImport.update({
    id: '/medical-chronology/',
    path: '/medical-chronology/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterChronologyIndexRoute =
  AppMasterChronologyIndexRouteImport.update({
    id: '/master-chronology/',
    path: '/master-chronology/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCaseManagementIndexRoute = AppCaseManagementIndexRouteImport.update({
  id: '/case-management/',
  path: '/case-management/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingChronologyIndexRoute =
  AppBillingChronologyIndexRouteImport.update({
    id: '/billing-chronology/',
    path: '/billing-chronology/',
    getParentRoute: () => AppRoute,
  } as any)
const AuthRegisterLayoutRoute = AuthRegisterLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRegisterRoute,
} as any)
const AuthPatientRegisterLayoutRoute =
  AuthPatientRegisterLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthPatientRegisterRoute,
  } as any)
const AuthLegalUserRegisterLayoutRoute =
  AuthLegalUserRegisterLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthLegalUserRegisterRoute,
  } as any)
const AppOrganizationManageAllUsersApprovalsRoute =
  AppOrganizationManageAllUsersApprovalsRouteImport.update({
    id: '/organization/manage-all-users-approvals',
    path: '/organization/manage-all-users-approvals',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationAdminManageApprovalsRoute =
  AppOrganizationAdminManageApprovalsRouteImport.update({
    id: '/organization-admin/manage-approvals',
    path: '/organization-admin/manage-approvals',
    getParentRoute: () => AppRoute,
  } as any)
const AppMedicalRecordsRequestRoute =
  AppMedicalRecordsRequestRouteImport.update({
    id: '/medical-records/request',
    path: '/medical-records/request',
    getParentRoute: () => AppRoute,
  } as any)
const AppKpisTimeSavingKpisRoute = AppKpisTimeSavingKpisRouteImport.update({
  id: '/time-saving-kpis',
  path: '/time-saving-kpis',
  getParentRoute: () => AppKpisRoute,
} as any)
const AppKpisTimeBasedKpisRoute = AppKpisTimeBasedKpisRouteImport.update({
  id: '/time-based-kpis',
  path: '/time-based-kpis',
  getParentRoute: () => AppKpisRoute,
} as any)
const AppKpisProductivityEfficiencyKpisRoute =
  AppKpisProductivityEfficiencyKpisRouteImport.update({
    id: '/productivity-efficiency-kpis',
    path: '/productivity-efficiency-kpis',
    getParentRoute: () => AppKpisRoute,
  } as any)
const AppKpisProductivityBasedKpisRoute =
  AppKpisProductivityBasedKpisRouteImport.update({
    id: '/productivity-based-kpis',
    path: '/productivity-based-kpis',
    getParentRoute: () => AppKpisRoute,
  } as any)
const AppKpisOperationalEfficiencyRoute =
  AppKpisOperationalEfficiencyRouteImport.update({
    id: '/operational-efficiency',
    path: '/operational-efficiency',
    getParentRoute: () => AppKpisRoute,
  } as any)
const AppKpisCustomerUsageEngagementRoute =
  AppKpisCustomerUsageEngagementRouteImport.update({
    id: '/customer-usage-engagement',
    path: '/customer-usage-engagement',
    getParentRoute: () => AppKpisRoute,
  } as any)
const AppKpisCustomerSatisfactionRetentionRoute =
  AppKpisCustomerSatisfactionRetentionRouteImport.update({
    id: '/customer-satisfaction-retention',
    path: '/customer-satisfaction-retention',
    getParentRoute: () => AppKpisRoute,
  } as any)
const AppKpisCostSavingRoiRoute = AppKpisCostSavingRoiRouteImport.update({
  id: '/cost-saving-roi',
  path: '/cost-saving-roi',
  getParentRoute: () => AppKpisRoute,
} as any)
const AppCaseManagementAddCaseRoute =
  AppCaseManagementAddCaseRouteImport.update({
    id: '/case-management/add-case',
    path: '/case-management/add-case',
    getParentRoute: () => AppRoute,
  } as any)
const AuthRegisterLayoutIndexRoute = AuthRegisterLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRegisterLayoutRoute,
} as any)
const AuthPatientRegisterLayoutIndexRoute =
  AuthPatientRegisterLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthPatientRegisterLayoutRoute,
  } as any)
const AuthLegalUserRegisterLayoutIndexRoute =
  AuthLegalUserRegisterLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLegalUserRegisterLayoutRoute,
  } as any)
const AppSettingsProfileOverviewIndexRoute =
  AppSettingsProfileOverviewIndexRouteImport.update({
    id: '/profile-overview/',
    path: '/profile-overview/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsAccountSettingsIndexRoute =
  AppSettingsAccountSettingsIndexRouteImport.update({
    id: '/account-settings/',
    path: '/account-settings/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AuthRegisterLayoutSupervisingDetailsRoute =
  AuthRegisterLayoutSupervisingDetailsRouteImport.update({
    id: '/supervising-details',
    path: '/supervising-details',
    getParentRoute: () => AuthRegisterLayoutRoute,
  } as any)
const AuthRegisterLayoutRoleSelectionRoute =
  AuthRegisterLayoutRoleSelectionRouteImport.update({
    id: '/role-selection',
    path: '/role-selection',
    getParentRoute: () => AuthRegisterLayoutRoute,
  } as any)
const AuthRegisterLayoutOtpValidationRoute =
  AuthRegisterLayoutOtpValidationRouteImport.update({
    id: '/otp-validation',
    path: '/otp-validation',
    getParentRoute: () => AuthRegisterLayoutRoute,
  } as any)
const AuthRegisterLayoutBusinessDetailsRoute =
  AuthRegisterLayoutBusinessDetailsRouteImport.update({
    id: '/business-details',
    path: '/business-details',
    getParentRoute: () => AuthRegisterLayoutRoute,
  } as any)
const AuthPatientRegisterLayoutBasicDetailsRoute =
  AuthPatientRegisterLayoutBasicDetailsRouteImport.update({
    id: '/basic-details',
    path: '/basic-details',
    getParentRoute: () => AuthPatientRegisterLayoutRoute,
  } as any)
const AuthLegalUserRegisterLayoutBasicDetailsRoute =
  AuthLegalUserRegisterLayoutBasicDetailsRouteImport.update({
    id: '/basic-details',
    path: '/basic-details',
    getParentRoute: () => AuthLegalUserRegisterLayoutRoute,
  } as any)
const AppSettingsProfileOverviewEditRoute =
  AppSettingsProfileOverviewEditRouteImport.update({
    id: '/profile-overview/edit',
    path: '/profile-overview/edit',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppOrganizationUsersIdRoute = AppOrganizationUsersIdRouteImport.update({
  id: '/organization/users/$id',
  path: '/organization/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRecordsViewIdRoute = AppMedicalRecordsViewIdRouteImport.update({
  id: '/medical-records/view/$id',
  path: '/medical-records/view/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRecordsCaseIdRoute = AppMedicalRecordsCaseIdRouteImport.update({
  id: '/medical-records/case/$id',
  path: '/medical-records/case/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalChronologyTimelineIdRoute =
  AppMedicalChronologyTimelineIdRouteImport.update({
    id: '/medical-chronology/timeline/$id',
    path: '/medical-chronology/timeline/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterChronologyTimelineIdRoute =
  AppMasterChronologyTimelineIdRouteImport.update({
    id: '/master-chronology/timeline/$id',
    path: '/master-chronology/timeline/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppCaseManagementViewIdRoute = AppCaseManagementViewIdRouteImport.update({
  id: '/case-management/view/$id',
  path: '/case-management/view/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseManagementTaskIdRoute = AppCaseManagementTaskIdRouteImport.update({
  id: '/case-management/task/$id',
  path: '/case-management/task/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseManagementEditIdRoute = AppCaseManagementEditIdRouteImport.update({
  id: '/case-management/edit/$id',
  path: '/case-management/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingChronologyTimelineIdRoute =
  AppBillingChronologyTimelineIdRouteImport.update({
    id: '/billing-chronology/timeline/$id',
    path: '/billing-chronology/timeline/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppMedicalChronologyTimelineEventChronologyIdIdRoute =
  AppMedicalChronologyTimelineEventChronologyIdIdRouteImport.update({
    id: '/medical-chronology/timeline-event/$chronologyId/$id',
    path: '/medical-chronology/timeline-event/$chronologyId/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppBillingChronologyBillingEventChronologyIDIdRoute =
  AppBillingChronologyBillingEventChronologyIDIdRouteImport.update({
    id: '/billing-chronology/billing-event/$chronologyID/$id',
    path: '/billing-chronology/billing-event/$chronologyID/$id',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/clearme-verification': typeof ClearmeVerificationRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/audit-reports': typeof AppAuditReportsRoute
  '/dashboard': typeof AppDashboardRoute
  '/help-support': typeof AppHelpSupportRoute
  '/kpis': typeof AppKpisRouteWithChildren
  '/my-tasks': typeof AppMyTasksRoute
  '/roles-management': typeof AppRolesManagementRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/user-management': typeof AppUserManagementRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/case-management/add-case': typeof AppCaseManagementAddCaseRoute
  '/kpis/cost-saving-roi': typeof AppKpisCostSavingRoiRoute
  '/kpis/customer-satisfaction-retention': typeof AppKpisCustomerSatisfactionRetentionRoute
  '/kpis/customer-usage-engagement': typeof AppKpisCustomerUsageEngagementRoute
  '/kpis/operational-efficiency': typeof AppKpisOperationalEfficiencyRoute
  '/kpis/productivity-based-kpis': typeof AppKpisProductivityBasedKpisRoute
  '/kpis/productivity-efficiency-kpis': typeof AppKpisProductivityEfficiencyKpisRoute
  '/kpis/time-based-kpis': typeof AppKpisTimeBasedKpisRoute
  '/kpis/time-saving-kpis': typeof AppKpisTimeSavingKpisRoute
  '/medical-records/request': typeof AppMedicalRecordsRequestRoute
  '/organization-admin/manage-approvals': typeof AppOrganizationAdminManageApprovalsRoute
  '/organization/manage-all-users-approvals': typeof AppOrganizationManageAllUsersApprovalsRoute
  '/auth/legal-user-register': typeof AuthLegalUserRegisterLayoutRouteWithChildren
  '/auth/patient-register': typeof AuthPatientRegisterLayoutRouteWithChildren
  '/auth/register': typeof AuthRegisterLayoutRouteWithChildren
  '/billing-chronology': typeof AppBillingChronologyIndexRoute
  '/case-management': typeof AppCaseManagementIndexRoute
  '/master-chronology': typeof AppMasterChronologyIndexRoute
  '/medical-chronology': typeof AppMedicalChronologyIndexRoute
  '/medical-records': typeof AppMedicalRecordsIndexRoute
  '/organization-admin': typeof AppOrganizationAdminIndexRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/billing-chronology/timeline/$id': typeof AppBillingChronologyTimelineIdRoute
  '/case-management/edit/$id': typeof AppCaseManagementEditIdRoute
  '/case-management/task/$id': typeof AppCaseManagementTaskIdRoute
  '/case-management/view/$id': typeof AppCaseManagementViewIdRoute
  '/master-chronology/timeline/$id': typeof AppMasterChronologyTimelineIdRoute
  '/medical-chronology/timeline/$id': typeof AppMedicalChronologyTimelineIdRoute
  '/medical-records/case/$id': typeof AppMedicalRecordsCaseIdRoute
  '/medical-records/view/$id': typeof AppMedicalRecordsViewIdRoute
  '/organization/users/$id': typeof AppOrganizationUsersIdRoute
  '/settings/profile-overview/edit': typeof AppSettingsProfileOverviewEditRoute
  '/auth/legal-user-register/basic-details': typeof AuthLegalUserRegisterLayoutBasicDetailsRoute
  '/auth/patient-register/basic-details': typeof AuthPatientRegisterLayoutBasicDetailsRoute
  '/auth/register/business-details': typeof AuthRegisterLayoutBusinessDetailsRoute
  '/auth/register/otp-validation': typeof AuthRegisterLayoutOtpValidationRoute
  '/auth/register/role-selection': typeof AuthRegisterLayoutRoleSelectionRoute
  '/auth/register/supervising-details': typeof AuthRegisterLayoutSupervisingDetailsRoute
  '/settings/account-settings': typeof AppSettingsAccountSettingsIndexRoute
  '/settings/profile-overview': typeof AppSettingsProfileOverviewIndexRoute
  '/auth/legal-user-register/': typeof AuthLegalUserRegisterLayoutIndexRoute
  '/auth/patient-register/': typeof AuthPatientRegisterLayoutIndexRoute
  '/auth/register/': typeof AuthRegisterLayoutIndexRoute
  '/billing-chronology/billing-event/$chronologyID/$id': typeof AppBillingChronologyBillingEventChronologyIDIdRoute
  '/medical-chronology/timeline-event/$chronologyId/$id': typeof AppMedicalChronologyTimelineEventChronologyIdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/clearme-verification': typeof ClearmeVerificationRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/audit-reports': typeof AppAuditReportsRoute
  '/dashboard': typeof AppDashboardRoute
  '/help-support': typeof AppHelpSupportRoute
  '/kpis': typeof AppKpisRouteWithChildren
  '/my-tasks': typeof AppMyTasksRoute
  '/roles-management': typeof AppRolesManagementRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/user-management': typeof AppUserManagementRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/case-management/add-case': typeof AppCaseManagementAddCaseRoute
  '/kpis/cost-saving-roi': typeof AppKpisCostSavingRoiRoute
  '/kpis/customer-satisfaction-retention': typeof AppKpisCustomerSatisfactionRetentionRoute
  '/kpis/customer-usage-engagement': typeof AppKpisCustomerUsageEngagementRoute
  '/kpis/operational-efficiency': typeof AppKpisOperationalEfficiencyRoute
  '/kpis/productivity-based-kpis': typeof AppKpisProductivityBasedKpisRoute
  '/kpis/productivity-efficiency-kpis': typeof AppKpisProductivityEfficiencyKpisRoute
  '/kpis/time-based-kpis': typeof AppKpisTimeBasedKpisRoute
  '/kpis/time-saving-kpis': typeof AppKpisTimeSavingKpisRoute
  '/medical-records/request': typeof AppMedicalRecordsRequestRoute
  '/organization-admin/manage-approvals': typeof AppOrganizationAdminManageApprovalsRoute
  '/organization/manage-all-users-approvals': typeof AppOrganizationManageAllUsersApprovalsRoute
  '/auth/legal-user-register': typeof AuthLegalUserRegisterLayoutIndexRoute
  '/auth/patient-register': typeof AuthPatientRegisterLayoutIndexRoute
  '/auth/register': typeof AuthRegisterLayoutIndexRoute
  '/billing-chronology': typeof AppBillingChronologyIndexRoute
  '/case-management': typeof AppCaseManagementIndexRoute
  '/master-chronology': typeof AppMasterChronologyIndexRoute
  '/medical-chronology': typeof AppMedicalChronologyIndexRoute
  '/medical-records': typeof AppMedicalRecordsIndexRoute
  '/organization-admin': typeof AppOrganizationAdminIndexRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/billing-chronology/timeline/$id': typeof AppBillingChronologyTimelineIdRoute
  '/case-management/edit/$id': typeof AppCaseManagementEditIdRoute
  '/case-management/task/$id': typeof AppCaseManagementTaskIdRoute
  '/case-management/view/$id': typeof AppCaseManagementViewIdRoute
  '/master-chronology/timeline/$id': typeof AppMasterChronologyTimelineIdRoute
  '/medical-chronology/timeline/$id': typeof AppMedicalChronologyTimelineIdRoute
  '/medical-records/case/$id': typeof AppMedicalRecordsCaseIdRoute
  '/medical-records/view/$id': typeof AppMedicalRecordsViewIdRoute
  '/organization/users/$id': typeof AppOrganizationUsersIdRoute
  '/settings/profile-overview/edit': typeof AppSettingsProfileOverviewEditRoute
  '/auth/legal-user-register/basic-details': typeof AuthLegalUserRegisterLayoutBasicDetailsRoute
  '/auth/patient-register/basic-details': typeof AuthPatientRegisterLayoutBasicDetailsRoute
  '/auth/register/business-details': typeof AuthRegisterLayoutBusinessDetailsRoute
  '/auth/register/otp-validation': typeof AuthRegisterLayoutOtpValidationRoute
  '/auth/register/role-selection': typeof AuthRegisterLayoutRoleSelectionRoute
  '/auth/register/supervising-details': typeof AuthRegisterLayoutSupervisingDetailsRoute
  '/settings/account-settings': typeof AppSettingsAccountSettingsIndexRoute
  '/settings/profile-overview': typeof AppSettingsProfileOverviewIndexRoute
  '/billing-chronology/billing-event/$chronologyID/$id': typeof AppBillingChronologyBillingEventChronologyIDIdRoute
  '/medical-chronology/timeline-event/$chronologyId/$id': typeof AppMedicalChronologyTimelineEventChronologyIdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/clearme-verification': typeof ClearmeVerificationRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/_app/audit-reports': typeof AppAuditReportsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help-support': typeof AppHelpSupportRoute
  '/_app/kpis': typeof AppKpisRouteWithChildren
  '/_app/my-tasks': typeof AppMyTasksRoute
  '/_app/roles-management': typeof AppRolesManagementRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/user-management': typeof AppUserManagementRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/_app/case-management/add-case': typeof AppCaseManagementAddCaseRoute
  '/_app/kpis/cost-saving-roi': typeof AppKpisCostSavingRoiRoute
  '/_app/kpis/customer-satisfaction-retention': typeof AppKpisCustomerSatisfactionRetentionRoute
  '/_app/kpis/customer-usage-engagement': typeof AppKpisCustomerUsageEngagementRoute
  '/_app/kpis/operational-efficiency': typeof AppKpisOperationalEfficiencyRoute
  '/_app/kpis/productivity-based-kpis': typeof AppKpisProductivityBasedKpisRoute
  '/_app/kpis/productivity-efficiency-kpis': typeof AppKpisProductivityEfficiencyKpisRoute
  '/_app/kpis/time-based-kpis': typeof AppKpisTimeBasedKpisRoute
  '/_app/kpis/time-saving-kpis': typeof AppKpisTimeSavingKpisRoute
  '/_app/medical-records/request': typeof AppMedicalRecordsRequestRoute
  '/_app/organization-admin/manage-approvals': typeof AppOrganizationAdminManageApprovalsRoute
  '/_app/organization/manage-all-users-approvals': typeof AppOrganizationManageAllUsersApprovalsRoute
  '/auth/legal-user-register': typeof AuthLegalUserRegisterRouteWithChildren
  '/auth/legal-user-register/_layout': typeof AuthLegalUserRegisterLayoutRouteWithChildren
  '/auth/patient-register': typeof AuthPatientRegisterRouteWithChildren
  '/auth/patient-register/_layout': typeof AuthPatientRegisterLayoutRouteWithChildren
  '/auth/register': typeof AuthRegisterRouteWithChildren
  '/auth/register/_layout': typeof AuthRegisterLayoutRouteWithChildren
  '/_app/billing-chronology/': typeof AppBillingChronologyIndexRoute
  '/_app/case-management/': typeof AppCaseManagementIndexRoute
  '/_app/master-chronology/': typeof AppMasterChronologyIndexRoute
  '/_app/medical-chronology/': typeof AppMedicalChronologyIndexRoute
  '/_app/medical-records/': typeof AppMedicalRecordsIndexRoute
  '/_app/organization-admin/': typeof AppOrganizationAdminIndexRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/billing-chronology/timeline/$id': typeof AppBillingChronologyTimelineIdRoute
  '/_app/case-management/edit/$id': typeof AppCaseManagementEditIdRoute
  '/_app/case-management/task/$id': typeof AppCaseManagementTaskIdRoute
  '/_app/case-management/view/$id': typeof AppCaseManagementViewIdRoute
  '/_app/master-chronology/timeline/$id': typeof AppMasterChronologyTimelineIdRoute
  '/_app/medical-chronology/timeline/$id': typeof AppMedicalChronologyTimelineIdRoute
  '/_app/medical-records/case/$id': typeof AppMedicalRecordsCaseIdRoute
  '/_app/medical-records/view/$id': typeof AppMedicalRecordsViewIdRoute
  '/_app/organization/users/$id': typeof AppOrganizationUsersIdRoute
  '/_app/settings/profile-overview/edit': typeof AppSettingsProfileOverviewEditRoute
  '/auth/legal-user-register/_layout/basic-details': typeof AuthLegalUserRegisterLayoutBasicDetailsRoute
  '/auth/patient-register/_layout/basic-details': typeof AuthPatientRegisterLayoutBasicDetailsRoute
  '/auth/register/_layout/business-details': typeof AuthRegisterLayoutBusinessDetailsRoute
  '/auth/register/_layout/otp-validation': typeof AuthRegisterLayoutOtpValidationRoute
  '/auth/register/_layout/role-selection': typeof AuthRegisterLayoutRoleSelectionRoute
  '/auth/register/_layout/supervising-details': typeof AuthRegisterLayoutSupervisingDetailsRoute
  '/_app/settings/account-settings/': typeof AppSettingsAccountSettingsIndexRoute
  '/_app/settings/profile-overview/': typeof AppSettingsProfileOverviewIndexRoute
  '/auth/legal-user-register/_layout/': typeof AuthLegalUserRegisterLayoutIndexRoute
  '/auth/patient-register/_layout/': typeof AuthPatientRegisterLayoutIndexRoute
  '/auth/register/_layout/': typeof AuthRegisterLayoutIndexRoute
  '/_app/billing-chronology/billing-event/$chronologyID/$id': typeof AppBillingChronologyBillingEventChronologyIDIdRoute
  '/_app/medical-chronology/timeline-event/$chronologyId/$id': typeof AppMedicalChronologyTimelineEventChronologyIdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/callback'
    | '/clearme-verification'
    | '/not-authorized'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/audit-reports'
    | '/dashboard'
    | '/help-support'
    | '/kpis'
    | '/my-tasks'
    | '/roles-management'
    | '/settings'
    | '/user-management'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/case-management/add-case'
    | '/kpis/cost-saving-roi'
    | '/kpis/customer-satisfaction-retention'
    | '/kpis/customer-usage-engagement'
    | '/kpis/operational-efficiency'
    | '/kpis/productivity-based-kpis'
    | '/kpis/productivity-efficiency-kpis'
    | '/kpis/time-based-kpis'
    | '/kpis/time-saving-kpis'
    | '/medical-records/request'
    | '/organization-admin/manage-approvals'
    | '/organization/manage-all-users-approvals'
    | '/auth/legal-user-register'
    | '/auth/patient-register'
    | '/auth/register'
    | '/billing-chronology'
    | '/case-management'
    | '/master-chronology'
    | '/medical-chronology'
    | '/medical-records'
    | '/organization-admin'
    | '/organization'
    | '/billing-chronology/timeline/$id'
    | '/case-management/edit/$id'
    | '/case-management/task/$id'
    | '/case-management/view/$id'
    | '/master-chronology/timeline/$id'
    | '/medical-chronology/timeline/$id'
    | '/medical-records/case/$id'
    | '/medical-records/view/$id'
    | '/organization/users/$id'
    | '/settings/profile-overview/edit'
    | '/auth/legal-user-register/basic-details'
    | '/auth/patient-register/basic-details'
    | '/auth/register/business-details'
    | '/auth/register/otp-validation'
    | '/auth/register/role-selection'
    | '/auth/register/supervising-details'
    | '/settings/account-settings'
    | '/settings/profile-overview'
    | '/auth/legal-user-register/'
    | '/auth/patient-register/'
    | '/auth/register/'
    | '/billing-chronology/billing-event/$chronologyID/$id'
    | '/medical-chronology/timeline-event/$chronologyId/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/callback'
    | '/clearme-verification'
    | '/not-authorized'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/audit-reports'
    | '/dashboard'
    | '/help-support'
    | '/kpis'
    | '/my-tasks'
    | '/roles-management'
    | '/settings'
    | '/user-management'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/case-management/add-case'
    | '/kpis/cost-saving-roi'
    | '/kpis/customer-satisfaction-retention'
    | '/kpis/customer-usage-engagement'
    | '/kpis/operational-efficiency'
    | '/kpis/productivity-based-kpis'
    | '/kpis/productivity-efficiency-kpis'
    | '/kpis/time-based-kpis'
    | '/kpis/time-saving-kpis'
    | '/medical-records/request'
    | '/organization-admin/manage-approvals'
    | '/organization/manage-all-users-approvals'
    | '/auth/legal-user-register'
    | '/auth/patient-register'
    | '/auth/register'
    | '/billing-chronology'
    | '/case-management'
    | '/master-chronology'
    | '/medical-chronology'
    | '/medical-records'
    | '/organization-admin'
    | '/organization'
    | '/billing-chronology/timeline/$id'
    | '/case-management/edit/$id'
    | '/case-management/task/$id'
    | '/case-management/view/$id'
    | '/master-chronology/timeline/$id'
    | '/medical-chronology/timeline/$id'
    | '/medical-records/case/$id'
    | '/medical-records/view/$id'
    | '/organization/users/$id'
    | '/settings/profile-overview/edit'
    | '/auth/legal-user-register/basic-details'
    | '/auth/patient-register/basic-details'
    | '/auth/register/business-details'
    | '/auth/register/otp-validation'
    | '/auth/register/role-selection'
    | '/auth/register/supervising-details'
    | '/settings/account-settings'
    | '/settings/profile-overview'
    | '/billing-chronology/billing-event/$chronologyID/$id'
    | '/medical-chronology/timeline-event/$chronologyId/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/callback'
    | '/clearme-verification'
    | '/not-authorized'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/_app/audit-reports'
    | '/_app/dashboard'
    | '/_app/help-support'
    | '/_app/kpis'
    | '/_app/my-tasks'
    | '/_app/roles-management'
    | '/_app/settings'
    | '/_app/user-management'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/_app/case-management/add-case'
    | '/_app/kpis/cost-saving-roi'
    | '/_app/kpis/customer-satisfaction-retention'
    | '/_app/kpis/customer-usage-engagement'
    | '/_app/kpis/operational-efficiency'
    | '/_app/kpis/productivity-based-kpis'
    | '/_app/kpis/productivity-efficiency-kpis'
    | '/_app/kpis/time-based-kpis'
    | '/_app/kpis/time-saving-kpis'
    | '/_app/medical-records/request'
    | '/_app/organization-admin/manage-approvals'
    | '/_app/organization/manage-all-users-approvals'
    | '/auth/legal-user-register'
    | '/auth/legal-user-register/_layout'
    | '/auth/patient-register'
    | '/auth/patient-register/_layout'
    | '/auth/register'
    | '/auth/register/_layout'
    | '/_app/billing-chronology/'
    | '/_app/case-management/'
    | '/_app/master-chronology/'
    | '/_app/medical-chronology/'
    | '/_app/medical-records/'
    | '/_app/organization-admin/'
    | '/_app/organization/'
    | '/_app/billing-chronology/timeline/$id'
    | '/_app/case-management/edit/$id'
    | '/_app/case-management/task/$id'
    | '/_app/case-management/view/$id'
    | '/_app/master-chronology/timeline/$id'
    | '/_app/medical-chronology/timeline/$id'
    | '/_app/medical-records/case/$id'
    | '/_app/medical-records/view/$id'
    | '/_app/organization/users/$id'
    | '/_app/settings/profile-overview/edit'
    | '/auth/legal-user-register/_layout/basic-details'
    | '/auth/patient-register/_layout/basic-details'
    | '/auth/register/_layout/business-details'
    | '/auth/register/_layout/otp-validation'
    | '/auth/register/_layout/role-selection'
    | '/auth/register/_layout/supervising-details'
    | '/_app/settings/account-settings/'
    | '/_app/settings/profile-overview/'
    | '/auth/legal-user-register/_layout/'
    | '/auth/patient-register/_layout/'
    | '/auth/register/_layout/'
    | '/_app/billing-chronology/billing-event/$chronologyID/$id'
    | '/_app/medical-chronology/timeline-event/$chronologyId/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ClearmeVerificationRoute: typeof ClearmeVerificationRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clearme-verification': {
      id: '/clearme-verification'
      path: '/clearme-verification'
      fullPath: '/clearme-verification'
      preLoaderRoute: typeof ClearmeVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/patient-register': {
      id: '/auth/patient-register'
      path: '/patient-register'
      fullPath: '/auth/patient-register'
      preLoaderRoute: typeof AuthPatientRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/legal-user-register': {
      id: '/auth/legal-user-register'
      path: '/legal-user-register'
      fullPath: '/auth/legal-user-register'
      preLoaderRoute: typeof AuthLegalUserRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/user-management': {
      id: '/_app/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AppUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles-management': {
      id: '/_app/roles-management'
      path: '/roles-management'
      fullPath: '/roles-management'
      preLoaderRoute: typeof AppRolesManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-tasks': {
      id: '/_app/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AppMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpis': {
      id: '/_app/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help-support': {
      id: '/_app/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof AppHelpSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-reports': {
      id: '/_app/audit-reports'
      path: '/audit-reports'
      fullPath: '/audit-reports'
      preLoaderRoute: typeof AppAuditReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization-admin/': {
      id: '/_app/organization-admin/'
      path: '/organization-admin'
      fullPath: '/organization-admin'
      preLoaderRoute: typeof AppOrganizationAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-records/': {
      id: '/_app/medical-records/'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof AppMedicalRecordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-chronology/': {
      id: '/_app/medical-chronology/'
      path: '/medical-chronology'
      fullPath: '/medical-chronology'
      preLoaderRoute: typeof AppMedicalChronologyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-chronology/': {
      id: '/_app/master-chronology/'
      path: '/master-chronology'
      fullPath: '/master-chronology'
      preLoaderRoute: typeof AppMasterChronologyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-management/': {
      id: '/_app/case-management/'
      path: '/case-management'
      fullPath: '/case-management'
      preLoaderRoute: typeof AppCaseManagementIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing-chronology/': {
      id: '/_app/billing-chronology/'
      path: '/billing-chronology'
      fullPath: '/billing-chronology'
      preLoaderRoute: typeof AppBillingChronologyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register/_layout': {
      id: '/auth/register/_layout'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterLayoutRouteImport
      parentRoute: typeof AuthRegisterRoute
    }
    '/auth/patient-register/_layout': {
      id: '/auth/patient-register/_layout'
      path: '/patient-register'
      fullPath: '/auth/patient-register'
      preLoaderRoute: typeof AuthPatientRegisterLayoutRouteImport
      parentRoute: typeof AuthPatientRegisterRoute
    }
    '/auth/legal-user-register/_layout': {
      id: '/auth/legal-user-register/_layout'
      path: '/legal-user-register'
      fullPath: '/auth/legal-user-register'
      preLoaderRoute: typeof AuthLegalUserRegisterLayoutRouteImport
      parentRoute: typeof AuthLegalUserRegisterRoute
    }
    '/_app/organization/manage-all-users-approvals': {
      id: '/_app/organization/manage-all-users-approvals'
      path: '/organization/manage-all-users-approvals'
      fullPath: '/organization/manage-all-users-approvals'
      preLoaderRoute: typeof AppOrganizationManageAllUsersApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization-admin/manage-approvals': {
      id: '/_app/organization-admin/manage-approvals'
      path: '/organization-admin/manage-approvals'
      fullPath: '/organization-admin/manage-approvals'
      preLoaderRoute: typeof AppOrganizationAdminManageApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-records/request': {
      id: '/_app/medical-records/request'
      path: '/medical-records/request'
      fullPath: '/medical-records/request'
      preLoaderRoute: typeof AppMedicalRecordsRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpis/time-saving-kpis': {
      id: '/_app/kpis/time-saving-kpis'
      path: '/time-saving-kpis'
      fullPath: '/kpis/time-saving-kpis'
      preLoaderRoute: typeof AppKpisTimeSavingKpisRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/time-based-kpis': {
      id: '/_app/kpis/time-based-kpis'
      path: '/time-based-kpis'
      fullPath: '/kpis/time-based-kpis'
      preLoaderRoute: typeof AppKpisTimeBasedKpisRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/productivity-efficiency-kpis': {
      id: '/_app/kpis/productivity-efficiency-kpis'
      path: '/productivity-efficiency-kpis'
      fullPath: '/kpis/productivity-efficiency-kpis'
      preLoaderRoute: typeof AppKpisProductivityEfficiencyKpisRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/productivity-based-kpis': {
      id: '/_app/kpis/productivity-based-kpis'
      path: '/productivity-based-kpis'
      fullPath: '/kpis/productivity-based-kpis'
      preLoaderRoute: typeof AppKpisProductivityBasedKpisRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/operational-efficiency': {
      id: '/_app/kpis/operational-efficiency'
      path: '/operational-efficiency'
      fullPath: '/kpis/operational-efficiency'
      preLoaderRoute: typeof AppKpisOperationalEfficiencyRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/customer-usage-engagement': {
      id: '/_app/kpis/customer-usage-engagement'
      path: '/customer-usage-engagement'
      fullPath: '/kpis/customer-usage-engagement'
      preLoaderRoute: typeof AppKpisCustomerUsageEngagementRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/customer-satisfaction-retention': {
      id: '/_app/kpis/customer-satisfaction-retention'
      path: '/customer-satisfaction-retention'
      fullPath: '/kpis/customer-satisfaction-retention'
      preLoaderRoute: typeof AppKpisCustomerSatisfactionRetentionRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/kpis/cost-saving-roi': {
      id: '/_app/kpis/cost-saving-roi'
      path: '/cost-saving-roi'
      fullPath: '/kpis/cost-saving-roi'
      preLoaderRoute: typeof AppKpisCostSavingRoiRouteImport
      parentRoute: typeof AppKpisRoute
    }
    '/_app/case-management/add-case': {
      id: '/_app/case-management/add-case'
      path: '/case-management/add-case'
      fullPath: '/case-management/add-case'
      preLoaderRoute: typeof AppCaseManagementAddCaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register/_layout/': {
      id: '/auth/register/_layout/'
      path: '/'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterLayoutIndexRouteImport
      parentRoute: typeof AuthRegisterLayoutRoute
    }
    '/auth/patient-register/_layout/': {
      id: '/auth/patient-register/_layout/'
      path: '/'
      fullPath: '/auth/patient-register/'
      preLoaderRoute: typeof AuthPatientRegisterLayoutIndexRouteImport
      parentRoute: typeof AuthPatientRegisterLayoutRoute
    }
    '/auth/legal-user-register/_layout/': {
      id: '/auth/legal-user-register/_layout/'
      path: '/'
      fullPath: '/auth/legal-user-register/'
      preLoaderRoute: typeof AuthLegalUserRegisterLayoutIndexRouteImport
      parentRoute: typeof AuthLegalUserRegisterLayoutRoute
    }
    '/_app/settings/profile-overview/': {
      id: '/_app/settings/profile-overview/'
      path: '/profile-overview'
      fullPath: '/settings/profile-overview'
      preLoaderRoute: typeof AppSettingsProfileOverviewIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account-settings/': {
      id: '/_app/settings/account-settings/'
      path: '/account-settings'
      fullPath: '/settings/account-settings'
      preLoaderRoute: typeof AppSettingsAccountSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/auth/register/_layout/supervising-details': {
      id: '/auth/register/_layout/supervising-details'
      path: '/supervising-details'
      fullPath: '/auth/register/supervising-details'
      preLoaderRoute: typeof AuthRegisterLayoutSupervisingDetailsRouteImport
      parentRoute: typeof AuthRegisterLayoutRoute
    }
    '/auth/register/_layout/role-selection': {
      id: '/auth/register/_layout/role-selection'
      path: '/role-selection'
      fullPath: '/auth/register/role-selection'
      preLoaderRoute: typeof AuthRegisterLayoutRoleSelectionRouteImport
      parentRoute: typeof AuthRegisterLayoutRoute
    }
    '/auth/register/_layout/otp-validation': {
      id: '/auth/register/_layout/otp-validation'
      path: '/otp-validation'
      fullPath: '/auth/register/otp-validation'
      preLoaderRoute: typeof AuthRegisterLayoutOtpValidationRouteImport
      parentRoute: typeof AuthRegisterLayoutRoute
    }
    '/auth/register/_layout/business-details': {
      id: '/auth/register/_layout/business-details'
      path: '/business-details'
      fullPath: '/auth/register/business-details'
      preLoaderRoute: typeof AuthRegisterLayoutBusinessDetailsRouteImport
      parentRoute: typeof AuthRegisterLayoutRoute
    }
    '/auth/patient-register/_layout/basic-details': {
      id: '/auth/patient-register/_layout/basic-details'
      path: '/basic-details'
      fullPath: '/auth/patient-register/basic-details'
      preLoaderRoute: typeof AuthPatientRegisterLayoutBasicDetailsRouteImport
      parentRoute: typeof AuthPatientRegisterLayoutRoute
    }
    '/auth/legal-user-register/_layout/basic-details': {
      id: '/auth/legal-user-register/_layout/basic-details'
      path: '/basic-details'
      fullPath: '/auth/legal-user-register/basic-details'
      preLoaderRoute: typeof AuthLegalUserRegisterLayoutBasicDetailsRouteImport
      parentRoute: typeof AuthLegalUserRegisterLayoutRoute
    }
    '/_app/settings/profile-overview/edit': {
      id: '/_app/settings/profile-overview/edit'
      path: '/profile-overview/edit'
      fullPath: '/settings/profile-overview/edit'
      preLoaderRoute: typeof AppSettingsProfileOverviewEditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/organization/users/$id': {
      id: '/_app/organization/users/$id'
      path: '/organization/users/$id'
      fullPath: '/organization/users/$id'
      preLoaderRoute: typeof AppOrganizationUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-records/view/$id': {
      id: '/_app/medical-records/view/$id'
      path: '/medical-records/view/$id'
      fullPath: '/medical-records/view/$id'
      preLoaderRoute: typeof AppMedicalRecordsViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-records/case/$id': {
      id: '/_app/medical-records/case/$id'
      path: '/medical-records/case/$id'
      fullPath: '/medical-records/case/$id'
      preLoaderRoute: typeof AppMedicalRecordsCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-chronology/timeline/$id': {
      id: '/_app/medical-chronology/timeline/$id'
      path: '/medical-chronology/timeline/$id'
      fullPath: '/medical-chronology/timeline/$id'
      preLoaderRoute: typeof AppMedicalChronologyTimelineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-chronology/timeline/$id': {
      id: '/_app/master-chronology/timeline/$id'
      path: '/master-chronology/timeline/$id'
      fullPath: '/master-chronology/timeline/$id'
      preLoaderRoute: typeof AppMasterChronologyTimelineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-management/view/$id': {
      id: '/_app/case-management/view/$id'
      path: '/case-management/view/$id'
      fullPath: '/case-management/view/$id'
      preLoaderRoute: typeof AppCaseManagementViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-management/task/$id': {
      id: '/_app/case-management/task/$id'
      path: '/case-management/task/$id'
      fullPath: '/case-management/task/$id'
      preLoaderRoute: typeof AppCaseManagementTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-management/edit/$id': {
      id: '/_app/case-management/edit/$id'
      path: '/case-management/edit/$id'
      fullPath: '/case-management/edit/$id'
      preLoaderRoute: typeof AppCaseManagementEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing-chronology/timeline/$id': {
      id: '/_app/billing-chronology/timeline/$id'
      path: '/billing-chronology/timeline/$id'
      fullPath: '/billing-chronology/timeline/$id'
      preLoaderRoute: typeof AppBillingChronologyTimelineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-chronology/timeline-event/$chronologyId/$id': {
      id: '/_app/medical-chronology/timeline-event/$chronologyId/$id'
      path: '/medical-chronology/timeline-event/$chronologyId/$id'
      fullPath: '/medical-chronology/timeline-event/$chronologyId/$id'
      preLoaderRoute: typeof AppMedicalChronologyTimelineEventChronologyIdIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing-chronology/billing-event/$chronologyID/$id': {
      id: '/_app/billing-chronology/billing-event/$chronologyID/$id'
      path: '/billing-chronology/billing-event/$chronologyID/$id'
      fullPath: '/billing-chronology/billing-event/$chronologyID/$id'
      preLoaderRoute: typeof AppBillingChronologyBillingEventChronologyIDIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppKpisRouteChildren {
  AppKpisCostSavingRoiRoute: typeof AppKpisCostSavingRoiRoute
  AppKpisCustomerSatisfactionRetentionRoute: typeof AppKpisCustomerSatisfactionRetentionRoute
  AppKpisCustomerUsageEngagementRoute: typeof AppKpisCustomerUsageEngagementRoute
  AppKpisOperationalEfficiencyRoute: typeof AppKpisOperationalEfficiencyRoute
  AppKpisProductivityBasedKpisRoute: typeof AppKpisProductivityBasedKpisRoute
  AppKpisProductivityEfficiencyKpisRoute: typeof AppKpisProductivityEfficiencyKpisRoute
  AppKpisTimeBasedKpisRoute: typeof AppKpisTimeBasedKpisRoute
  AppKpisTimeSavingKpisRoute: typeof AppKpisTimeSavingKpisRoute
}

const AppKpisRouteChildren: AppKpisRouteChildren = {
  AppKpisCostSavingRoiRoute: AppKpisCostSavingRoiRoute,
  AppKpisCustomerSatisfactionRetentionRoute:
    AppKpisCustomerSatisfactionRetentionRoute,
  AppKpisCustomerUsageEngagementRoute: AppKpisCustomerUsageEngagementRoute,
  AppKpisOperationalEfficiencyRoute: AppKpisOperationalEfficiencyRoute,
  AppKpisProductivityBasedKpisRoute: AppKpisProductivityBasedKpisRoute,
  AppKpisProductivityEfficiencyKpisRoute:
    AppKpisProductivityEfficiencyKpisRoute,
  AppKpisTimeBasedKpisRoute: AppKpisTimeBasedKpisRoute,
  AppKpisTimeSavingKpisRoute: AppKpisTimeSavingKpisRoute,
}

const AppKpisRouteWithChildren =
  AppKpisRoute._addFileChildren(AppKpisRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsProfileOverviewEditRoute: typeof AppSettingsProfileOverviewEditRoute
  AppSettingsAccountSettingsIndexRoute: typeof AppSettingsAccountSettingsIndexRoute
  AppSettingsProfileOverviewIndexRoute: typeof AppSettingsProfileOverviewIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsProfileOverviewEditRoute: AppSettingsProfileOverviewEditRoute,
  AppSettingsAccountSettingsIndexRoute: AppSettingsAccountSettingsIndexRoute,
  AppSettingsProfileOverviewIndexRoute: AppSettingsProfileOverviewIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAuditReportsRoute: typeof AppAuditReportsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpSupportRoute: typeof AppHelpSupportRoute
  AppKpisRoute: typeof AppKpisRouteWithChildren
  AppMyTasksRoute: typeof AppMyTasksRoute
  AppRolesManagementRoute: typeof AppRolesManagementRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppUserManagementRoute: typeof AppUserManagementRoute
  AppCaseManagementAddCaseRoute: typeof AppCaseManagementAddCaseRoute
  AppMedicalRecordsRequestRoute: typeof AppMedicalRecordsRequestRoute
  AppOrganizationAdminManageApprovalsRoute: typeof AppOrganizationAdminManageApprovalsRoute
  AppOrganizationManageAllUsersApprovalsRoute: typeof AppOrganizationManageAllUsersApprovalsRoute
  AppBillingChronologyIndexRoute: typeof AppBillingChronologyIndexRoute
  AppCaseManagementIndexRoute: typeof AppCaseManagementIndexRoute
  AppMasterChronologyIndexRoute: typeof AppMasterChronologyIndexRoute
  AppMedicalChronologyIndexRoute: typeof AppMedicalChronologyIndexRoute
  AppMedicalRecordsIndexRoute: typeof AppMedicalRecordsIndexRoute
  AppOrganizationAdminIndexRoute: typeof AppOrganizationAdminIndexRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
  AppBillingChronologyTimelineIdRoute: typeof AppBillingChronologyTimelineIdRoute
  AppCaseManagementEditIdRoute: typeof AppCaseManagementEditIdRoute
  AppCaseManagementTaskIdRoute: typeof AppCaseManagementTaskIdRoute
  AppCaseManagementViewIdRoute: typeof AppCaseManagementViewIdRoute
  AppMasterChronologyTimelineIdRoute: typeof AppMasterChronologyTimelineIdRoute
  AppMedicalChronologyTimelineIdRoute: typeof AppMedicalChronologyTimelineIdRoute
  AppMedicalRecordsCaseIdRoute: typeof AppMedicalRecordsCaseIdRoute
  AppMedicalRecordsViewIdRoute: typeof AppMedicalRecordsViewIdRoute
  AppOrganizationUsersIdRoute: typeof AppOrganizationUsersIdRoute
  AppBillingChronologyBillingEventChronologyIDIdRoute: typeof AppBillingChronologyBillingEventChronologyIDIdRoute
  AppMedicalChronologyTimelineEventChronologyIdIdRoute: typeof AppMedicalChronologyTimelineEventChronologyIdIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditReportsRoute: AppAuditReportsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpSupportRoute: AppHelpSupportRoute,
  AppKpisRoute: AppKpisRouteWithChildren,
  AppMyTasksRoute: AppMyTasksRoute,
  AppRolesManagementRoute: AppRolesManagementRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppUserManagementRoute: AppUserManagementRoute,
  AppCaseManagementAddCaseRoute: AppCaseManagementAddCaseRoute,
  AppMedicalRecordsRequestRoute: AppMedicalRecordsRequestRoute,
  AppOrganizationAdminManageApprovalsRoute:
    AppOrganizationAdminManageApprovalsRoute,
  AppOrganizationManageAllUsersApprovalsRoute:
    AppOrganizationManageAllUsersApprovalsRoute,
  AppBillingChronologyIndexRoute: AppBillingChronologyIndexRoute,
  AppCaseManagementIndexRoute: AppCaseManagementIndexRoute,
  AppMasterChronologyIndexRoute: AppMasterChronologyIndexRoute,
  AppMedicalChronologyIndexRoute: AppMedicalChronologyIndexRoute,
  AppMedicalRecordsIndexRoute: AppMedicalRecordsIndexRoute,
  AppOrganizationAdminIndexRoute: AppOrganizationAdminIndexRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
  AppBillingChronologyTimelineIdRoute: AppBillingChronologyTimelineIdRoute,
  AppCaseManagementEditIdRoute: AppCaseManagementEditIdRoute,
  AppCaseManagementTaskIdRoute: AppCaseManagementTaskIdRoute,
  AppCaseManagementViewIdRoute: AppCaseManagementViewIdRoute,
  AppMasterChronologyTimelineIdRoute: AppMasterChronologyTimelineIdRoute,
  AppMedicalChronologyTimelineIdRoute: AppMedicalChronologyTimelineIdRoute,
  AppMedicalRecordsCaseIdRoute: AppMedicalRecordsCaseIdRoute,
  AppMedicalRecordsViewIdRoute: AppMedicalRecordsViewIdRoute,
  AppOrganizationUsersIdRoute: AppOrganizationUsersIdRoute,
  AppBillingChronologyBillingEventChronologyIDIdRoute:
    AppBillingChronologyBillingEventChronologyIDIdRoute,
  AppMedicalChronologyTimelineEventChronologyIdIdRoute:
    AppMedicalChronologyTimelineEventChronologyIdIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthLegalUserRegisterLayoutRouteChildren {
  AuthLegalUserRegisterLayoutBasicDetailsRoute: typeof AuthLegalUserRegisterLayoutBasicDetailsRoute
  AuthLegalUserRegisterLayoutIndexRoute: typeof AuthLegalUserRegisterLayoutIndexRoute
}

const AuthLegalUserRegisterLayoutRouteChildren: AuthLegalUserRegisterLayoutRouteChildren =
  {
    AuthLegalUserRegisterLayoutBasicDetailsRoute:
      AuthLegalUserRegisterLayoutBasicDetailsRoute,
    AuthLegalUserRegisterLayoutIndexRoute:
      AuthLegalUserRegisterLayoutIndexRoute,
  }

const AuthLegalUserRegisterLayoutRouteWithChildren =
  AuthLegalUserRegisterLayoutRoute._addFileChildren(
    AuthLegalUserRegisterLayoutRouteChildren,
  )

interface AuthLegalUserRegisterRouteChildren {
  AuthLegalUserRegisterLayoutRoute: typeof AuthLegalUserRegisterLayoutRouteWithChildren
}

const AuthLegalUserRegisterRouteChildren: AuthLegalUserRegisterRouteChildren = {
  AuthLegalUserRegisterLayoutRoute:
    AuthLegalUserRegisterLayoutRouteWithChildren,
}

const AuthLegalUserRegisterRouteWithChildren =
  AuthLegalUserRegisterRoute._addFileChildren(
    AuthLegalUserRegisterRouteChildren,
  )

interface AuthPatientRegisterLayoutRouteChildren {
  AuthPatientRegisterLayoutBasicDetailsRoute: typeof AuthPatientRegisterLayoutBasicDetailsRoute
  AuthPatientRegisterLayoutIndexRoute: typeof AuthPatientRegisterLayoutIndexRoute
}

const AuthPatientRegisterLayoutRouteChildren: AuthPatientRegisterLayoutRouteChildren =
  {
    AuthPatientRegisterLayoutBasicDetailsRoute:
      AuthPatientRegisterLayoutBasicDetailsRoute,
    AuthPatientRegisterLayoutIndexRoute: AuthPatientRegisterLayoutIndexRoute,
  }

const AuthPatientRegisterLayoutRouteWithChildren =
  AuthPatientRegisterLayoutRoute._addFileChildren(
    AuthPatientRegisterLayoutRouteChildren,
  )

interface AuthPatientRegisterRouteChildren {
  AuthPatientRegisterLayoutRoute: typeof AuthPatientRegisterLayoutRouteWithChildren
}

const AuthPatientRegisterRouteChildren: AuthPatientRegisterRouteChildren = {
  AuthPatientRegisterLayoutRoute: AuthPatientRegisterLayoutRouteWithChildren,
}

const AuthPatientRegisterRouteWithChildren =
  AuthPatientRegisterRoute._addFileChildren(AuthPatientRegisterRouteChildren)

interface AuthRegisterLayoutRouteChildren {
  AuthRegisterLayoutBusinessDetailsRoute: typeof AuthRegisterLayoutBusinessDetailsRoute
  AuthRegisterLayoutOtpValidationRoute: typeof AuthRegisterLayoutOtpValidationRoute
  AuthRegisterLayoutRoleSelectionRoute: typeof AuthRegisterLayoutRoleSelectionRoute
  AuthRegisterLayoutSupervisingDetailsRoute: typeof AuthRegisterLayoutSupervisingDetailsRoute
  AuthRegisterLayoutIndexRoute: typeof AuthRegisterLayoutIndexRoute
}

const AuthRegisterLayoutRouteChildren: AuthRegisterLayoutRouteChildren = {
  AuthRegisterLayoutBusinessDetailsRoute:
    AuthRegisterLayoutBusinessDetailsRoute,
  AuthRegisterLayoutOtpValidationRoute: AuthRegisterLayoutOtpValidationRoute,
  AuthRegisterLayoutRoleSelectionRoute: AuthRegisterLayoutRoleSelectionRoute,
  AuthRegisterLayoutSupervisingDetailsRoute:
    AuthRegisterLayoutSupervisingDetailsRoute,
  AuthRegisterLayoutIndexRoute: AuthRegisterLayoutIndexRoute,
}

const AuthRegisterLayoutRouteWithChildren =
  AuthRegisterLayoutRoute._addFileChildren(AuthRegisterLayoutRouteChildren)

interface AuthRegisterRouteChildren {
  AuthRegisterLayoutRoute: typeof AuthRegisterLayoutRouteWithChildren
}

const AuthRegisterRouteChildren: AuthRegisterRouteChildren = {
  AuthRegisterLayoutRoute: AuthRegisterLayoutRouteWithChildren,
}

const AuthRegisterRouteWithChildren = AuthRegisterRoute._addFileChildren(
  AuthRegisterRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLegalUserRegisterRoute: typeof AuthLegalUserRegisterRouteWithChildren
  AuthPatientRegisterRoute: typeof AuthPatientRegisterRouteWithChildren
  AuthRegisterRoute: typeof AuthRegisterRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLegalUserRegisterRoute: AuthLegalUserRegisterRouteWithChildren,
  AuthPatientRegisterRoute: AuthPatientRegisterRouteWithChildren,
  AuthRegisterRoute: AuthRegisterRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ClearmeVerificationRoute: ClearmeVerificationRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfUseRoute: TermsOfUseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
